// Theme Toggle
const themeToggle = document.getElementById('themeToggle');

themeToggle.addEventListener('click', () => {
    document.body.classList.toggle('dark-mode');
    const isDark = document.body.classList.contains('dark-mode');
    themeToggle.innerHTML = isDark ? '<i class="fas fa-sun"></i>' : '<i class="fas fa-moon"></i>';
    localStorage.setItem('theme', isDark ? 'dark' : 'light');
});

// Load saved theme
if (localStorage.getItem('theme') === 'dark') {
    document.body.classList.add('dark-mode');
    themeToggle.innerHTML = '<i class="fas fa-sun"></i>';
}

// Marker Animation Loop
let progress = 0;
const markerGroup = document.getElementById('markerGroup');
const etaMinutes = document.getElementById('etaMinutes');
const distanceText = document.getElementById('distanceText');
const etaText = document.getElementById('etaText');

function getMarkerPosition(prog) {
    const p = prog / 100;
    
    if (p < 0.2) return { x: 50 + (70 * (p/0.2)), y: 150 };
    if (p < 0.4) return { x: 120, y: 150 + (100 * ((p-0.2)/0.2)) };
    if (p < 0.7) return { x: 120 + (130 * ((p-0.4)/0.3)), y: 250 - (20 * ((p-0.4)/0.3)) };
    if (p < 0.9) return { x: 250, y: 230 - (130 * ((p-0.7)/0.2)) };
    return { x: 250 + (100 * ((p-0.9)/0.1)), y: 100 };
}

setInterval(() => {
    progress = (progress + 0.2) % 100;
    const pos = getMarkerPosition(progress);
    markerGroup.setAttribute('transform', `translate(${pos.x}, ${pos.y})`);

    // Update ETA
    const remainingPercent = 100 - progress;
    const eta = Math.ceil((remainingPercent / 100) * 15);
    const distance = ((remainingPercent / 100) * 3.5).toFixed(1);
    
    etaMinutes.textContent = eta;
    distanceText.textContent = `(${distance} km)`;
    etaText.textContent = eta + ' min';

    // Update arrival time
    const now = new Date();
    const arrival = new Date(now.getTime() + eta * 60000);
    document.getElementById('arrivalTime').textContent = arrival.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});
}, 50);

// Report Button
document.getElementById('reportBtn').addEventListener('click', function() {
    this.disabled = true;
    this.innerHTML = '<div class="spinner"></div><span>Generating...</span>';

    setTimeout(() => {
        const tripData = `TRIP REPORT SUMMARY
-------------------
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

DRIVER DETAILS
Name: Alison Mcferry
Vehicle: Toyota Camry (HSW 829)
Rating: 4.9 Stars

TRIP STATUS
Status: In Progress
Current ETA: ${document.getElementById('etaMinutes').textContent} mins
Distance Remaining: ${distanceText.textContent}

ROUTE
From: Adam Street, 4103
To: Balfe Street, 4245

-------------------
Generated by Location Tracker App`;

        const blob = new Blob([tripData], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Trip_Report_${Date.now()}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        this.disabled = false;
        this.innerHTML = '<i class="fas fa-file-pdf"></i><span>Trip Report</span>';
    }, 800);
});

// Action Buttons
document.getElementById('messageBtn').addEventListener('click', () => {
    alert('Opening message with Alison Mcferry...');
});

document.getElementById('callBtn').addEventListener('click', () => {
    alert('Calling Alison Mcferry...');
});

document.getElementById('backBtn').addEventListener('click', () => {
    alert('Going back...');
});

document.getElementById('searchBtn').addEventListener('click', () => {
    alert('Opening search...');
});

// Map Controls
document.getElementById('navigationBtn').addEventListener('click', () => {
    alert('Opening full navigation...');
});

document.getElementById('zoomInBtn').addEventListener('click', () => {
    alert('Zooming in...');
});

document.getElementById('zoomOutBtn').addEventListener('click', () => {
    alert('Zooming out...');
});

// Navigation items
document.querySelectorAll('.nav-item').forEach(item => {
    item.addEventListener('click', function() {
        document.querySelectorAll('.nav-item').forEach(i => i.classList.remove('active'));
        this.classList.add('active');
    });
});
